config/routes.rb
TodoApp3::Application.routes.draw do
  get '/signup', to: 'users#new', as: 'signup'
  get '/signin', to: 'sessions#new', as: 'signin'
  get '/signout', to: 'sessions#destroy', as: 'signout'

  resources :tasks
  resources :sessions
  resources :users

  root to: "tasks#index"

  

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tasks, dependent: :destroy
	has_secure_password
	before_create { generate_token(:auth_token) }

	validates :email, uniqueness: true

	private

		def generate_token(column)
			begin
				self[column] = SecureRandom.urlsafe_base64			
			end while User.exists?(column => self[column])
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user


  def current_user
  	@current_user = User.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new	
	end

 	def create
	  	user = User.find_by_email(params[:email])
  		if user && user.authenticate(params[:password])
	  		if params[:remember_me]
	  			cookies.permanent[:auth_token] = user.auth_token
	  		else
	  			cookies[:auth_token] = user.auth_token
	  		end
	  		redirect_to tasks_path, notice:  "Signed in"
	  	else
	  		flash.now[:notice] = "Error signing in"
	  		render 'new'
	  	end
	end

	def destroy
		cookies.delete(:auth_token)
		flash[:notice] = "Signed out"
		redirect_to tasks_path
	end

  private

  	def session_params
  		params.require(:session).permit(:email, :password)  		
  	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    if current_user
    	@incomplete = current_user.tasks.where(complete: false)
      @complete = current_user.tasks.where(complete: true)
    end
  end

  def create
  	@task = current_user.tasks.new(task_params)
  	if @task.save
  		flash[:success] = "Task added succesfully"
  	else
  		flash[:notice] = "Task failed to be added"
  	end
  	redirect_to tasks_path
  end

  def update
  	@task = current_user.tasks.find(params[:id])
  	@task.update_attributes!(task_params)
  	respond_to do |format|
  		format.html { redirect_to tasks_path }
  		format.js
  	end
  end

  def destroy
  	@task = current_user.tasks.find(params[:id])
  	@task.destroy
  	respond_to do |format|
  		format.html { redirect_to tasks_path }
  		format.js
  	end
  end

  private

  	def task_params
  		params.require(:task).permit(:content, :complete)
  	end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		#if params[:remember_me]
  		cookies.permanent[:auth_token] = @user.auth_token
  		#else
  		#	cookies[:auth_token] = @user.auth_token
  		#end
  		flash[:notice] = "Signup executed successfully"
	  	redirect_to users_path  	
  	else
  		flash[:notice] = "Signup failed"
  		render 'new'
  	end
  end

  def index
  	@users = User.all
  end

  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp3</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<ul>
		<% if current_user %>
			<div id="logged_as">Logged in as <%= current_user.email %></div>
			<li class="navbar_item"><%= link_to "Sign out", signout_path %></li>
		<% else %>
			<li class="navbar_item"><%= link_to "Sign in", signin_path %></li>
			<li class="navbar_item"><%= link_to "Sign up", signup_path %></li>
		<% end %>
	</ul>

	<%= flash.each do |name, msg| %>
		<% content_tag :div, msg, id: "flash_#{name}" %>
	<% end %>

	<%= yield %>

</body>
</html>

app/views/tasks/_task.html.erb
<%= form_for task, remote: true do |f| %>
	<%= f.check_box :complete %>
	<%= f.label :complete, task.content %>
	<%= link_to "(remove)", task, class: "remove", method: :delete, remote: true %>
<% end %>

app/views/tasks/destroy.js.erb
jQuery(document).ready(function($) {
	$('#edit_task_<%= @task.id %>').remove();
});

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<%= form_for Task.new do |f| %>
	<%= f.text_field :content %>
	<%= f.submit "Add Task" %>
<% end %>

<% if current_user %>
	<h3>Incomplete Tasks</h3>
	<div id="incomplete_tasks">
		<%= render @incomplete %>
	</div>

	<h3>Complete Tasks</h3>
	<div id="complete_tasks">
		<%= render @complete %>
	</div>
<% else %>
	<p>Sign in or create an account to see tasks.</p>
<% end %>

app/views/tasks/update.js.erb
jQuery(document).ready(function($){
	<% if @task.complete? %>
		$('#edit_task_<%= @task.id %>').appendTo('#complete_tasks');
	<% else %>
		$('#edit_task_<%= @task.id %>').appendTo('#incomplete_tasks');
	<% end %>
});

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>

<%= form_for @user do |f| %>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<br>

	<%= f.label :password %>
	<%= f.password_field :password %>
	<br>

	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
	<br>

	<%= f.submit "Sign Up" %>
<% end %>